import { supabase } from './supabase-client.js';
import { signIn, signOut, signUp, resetPassword } from './auth.js';
import { gameApi } from './game-api.js';
import { readLegacySave } from './import-validator.js';

const root = document.querySelector('#app');
const PRODUCT = { normal:['Normal Pack',200,'3 cards · standard odds'], plus:['Plus Pack',null,'Green+ guaranteed'], premium:['Premium Pack',null,'Blue+ guaranteed'], elite:['Elite Pack',null,'Red+ guaranteed'], hanger:['Hanger Box',null,'3 packs · Neon Nights'], value:['Value Box',null,'5 packs · Black Ice + APEX'], hobby:['Hobby Box',null,'8 packs · premium guarantees'] };
const NAMES = {kane:'Harry Kane',dembele:'Ousmane Dembélé',dowman:'Max Dowman',haaland:'Erling Haaland',estevao:'Estêvão Willian',karl:'Lennart Karl',vini:'Vinícius Jr.',palmer:'Cole Palmer',messi:'Lionel Messi',ronaldo:'Cristiano Ronaldo',yamal:'Lamine Yamal',bellingham:'Jude Bellingham',zidane:'Zinedine Zidane'};
let state=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const inv=()=>Object.fromEntries((state?.inventory||[]).map(x=>[x.product,x.quantity]));
const cardInfo=code=>{const [type,player]=String(code).split(':');return {type,player,name:NAMES[player]||'APEX Card'};};
const appShell=()=>document.querySelector('.app-shell');
function chrome(show){appShell().classList.toggle('account-screen',!show);document.querySelector('.topbar').hidden=!show;document.querySelector('.bottom-nav').hidden=!show;}
function card(code,count=''){const c=cardInfo(code),img=['base','green','blue','apex','red'].includes(c.type)?`assets/cards/debut-edition/base/${c.player}.png`:'';return `<article class="account-card ${c.type}">${img?`<img src="${img}" alt="${esc(c.name)}">`:'<div class="card-shine">A</div>'}<div class="account-card-meta"><small>${esc(c.type==='theapex'?'THE APEX':c.type)}</small><strong>${esc(c.name)}</strong>${count!==''?`<span>×${count}</span>`:''}</div></article>`;}
function product(key){const [name,,copy]=PRODUCT[key]||[key,null,''];return `<div class="product-visual account-product ${key}"><b>APEX</b><small>${esc(name)}</small><i>${esc(copy)}</i></div>`;}
function setChrome(){document.querySelector('#coinBalance').textContent=Number(state.wallet?.coin_balance||0).toLocaleString();document.querySelector('.profile-dot').textContent=(state.profile?.display_name||'P')[0].toUpperCase();document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>route(b.dataset.route));}
function auth(mode='signin',notice=''){
  chrome(false);const signup=mode==='signup',reset=mode==='reset';
  root.innerHTML=`<section class="account-layout"><aside class="account-art"><div class="account-copy"><p class="eyebrow">APEX UCL DEBUT EDITION 26/27</p><h1>Every pull.<br><em>Your account.</em></h1><p>Your binder, coins and unopened packs are safely saved to your APEX account—on phone, tablet and desktop.</p><div class="account-cards"><i>A</i><i>APEX</i><i>26/27</i></div></div></aside><section class="account-panel"><div class="account-panel-inner"><p class="eyebrow">${reset?'ACCOUNT RECOVERY':signup?'NEW COLLECTOR':'WELCOME BACK'}</p><h2>${reset?'Reset your password':signup?'Start your APEX account':'Sign in to APEX'}</h2><p class="muted">${reset?'We’ll email a secure reset link.':signup?'Your card collection follows you everywhere.':'Continue your Debut Edition journey.'}</p>${!reset?`<div class="auth-tabs"><button class="${!signup?'active':''}" data-auth="signin">Sign in</button><button class="${signup?'active':''}" data-auth="signup">Create account</button></div>`:''}<form id="authForm" class="account-form"><label>Email<input required autocomplete="email" type="email" name="email" placeholder="you@email.com"></label>${!reset?`<label>Password<input required minlength="8" autocomplete="${signup?'new-password':'current-password'}" type="password" name="password" placeholder="At least 8 characters"></label>`:''}<button class="primary account-submit">${reset?'Send reset link':signup?'Create account →':'Sign in →'}</button></form>${!signup&&!reset?'<button class="text-button" data-auth="reset">Forgot your password?</button>':''}${reset?'<button class="text-button" data-auth="signin">← Back to sign in</button>':''}${notice?`<p class="form-message">${esc(notice)}</p>`:''}<p class="account-footnote">Your email is never visible to other collectors.</p></div></section></section>`;
  root.querySelectorAll('[data-auth]').forEach(b=>b.onclick=()=>auth(b.dataset.auth));
  root.querySelector('#authForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{if(reset){await resetPassword(f.get('email'));return auth('signin','Check your email for the reset link.');}if(signup){const result=await signUp(f.get('email'),f.get('password'));if(!result?.session)return auth('signin','Check your email and confirm your address. The confirmation button will return you to APEX.');}else await signIn(f.get('email'),f.get('password'));boot();}catch(err){auth(mode,err.message);}};
}
function onboarding(notice=''){
  chrome(false);let legacy;try{legacy=readLegacySave();}catch{}
  root.innerHTML=`<section class="onboarding page"><p class="eyebrow">WELCOME TO APEX</p><h1>Make this binder yours.</h1><p class="muted">Choose your collector name, then choose how to begin.</p><div class="onboarding-grid"><form id="onboard" class="generic-card onboarding-form"><label>Collector name<input required maxlength="40" name="name" placeholder="How should APEX know you?"></label><label>Username <span>optional</span><input pattern="[A-Za-z0-9_]{3,24}" name="username" placeholder="3–24 letters, numbers or _"></label><button class="primary">Start a new account →</button>${notice?`<p class="form-message">${esc(notice)}</p>`:''}</form><article class="starter-choice"><p class="eyebrow">FIRST SEASON</p><h2>Start with the beta collection</h2><p>Starter coins and sealed product are applied server-side—not on this device.</p><b>◉ Secure online save</b></article>${legacy?`<button class="import-choice" id="import"><p class="eyebrow">EXISTING PLAYER</p><h2>Import this device’s save</h2><p>${Number(legacy.coins).toLocaleString()} coins · ${Object.keys(legacy.cards).length} card entries</p><b>Review & import →</b></button>`:'<article class="import-choice muted"><p class="eyebrow">EXISTING PLAYER</p><h2>No local save on this device</h2><p>Start fresh, then play this account everywhere.</p></article>'}</div></section>`;
  root.querySelector('#onboard').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{state=await gameApi('onboard',{displayName:f.get('name'),username:f.get('username')});route('home');}catch(err){onboarding(err.message);}};
  root.querySelector('#import')?.addEventListener('click',async()=>{if(!confirm('Import this local APEX save once? This cannot be undone.'))return;try{state=await gameApi('import.localSave',{save:legacy});route('home');}catch(err){onboarding(err.message);}});
}
async function refresh(){state=await gameApi('bootstrap');}
function home(){const inventory=inv(),unique=state.cards?.length||0,total=state.cards?.reduce((a,c)=>a+c.quantity,0)||0;root.innerHTML=`<section class="page account-home"><section class="server-hero"><div><p class="eyebrow">${esc(state.profile?.display_name||'COLLECTOR')} · ONLINE BINDER</p><h1>Ready for your<br><em>next pull?</em></h1><p>${inventory.normal||0} Normal Packs and ${inventory.hobby||0} Hobby Boxes are sealed on your account.</p><button class="primary" data-go="open">Open packs →</button></div><div class="server-hero-cards">${card(state.cards?.[0]?.id||'base:estevao')}${card(state.cards?.[1]?.id||'blue:yamal')}</div></section><section class="account-stat-row"><article><span>◉</span><div><small>COINS</small><b>${Number(state.wallet?.coin_balance||0).toLocaleString()}</b></div></article><article><span>▱</span><div><small>CARDS OWNED</small><b>${total}</b></div></article><article><span>✦</span><div><small>UNIQUE CARDS</small><b>${unique}/124</b></div></article></section><div class="account-section-title"><div><p class="eyebrow">SEALED INVENTORY</p><h2>Choose your next rip</h2></div><button class="ghost" data-go="open">View all</button></div><section class="account-product-grid">${Object.keys(PRODUCT).filter(k=>inventory[k]).slice(0,4).map(k=>`<button class="owned-product" data-open="${k}">${product(k)}<b>${PRODUCT[k][0]} · ×${inventory[k]} sealed</b><em>Open →</em></button>`).join('')||'<div class="empty-state">No sealed products yet. The Store has Normal Packs.</div>'}</section><div class="account-section-title"><div><p class="eyebrow">YOUR BINDER</p><h2>Recent cards</h2></div><button class="ghost" data-go="collection">View binder</button></div><section class="account-card-grid">${state.cards?.slice(0,6).map(c=>card(c.id,c.quantity)).join('')||'<div class="empty-state">Your first cards will appear here after an opening.</div>'}</section></section>`;bind();}
function open(){const inventory=inv();root.innerHTML=`<section class="page"><div class="page-title-row"><div><p class="eyebrow">SEALED INVENTORY</p><h1>Open packs</h1></div></div><p class="notice">Packs are reserved by the server before you reveal them. Refreshing cannot change a pull.</p><section class="account-product-grid open-grid">${Object.keys(PRODUCT).map(k=>`<article class="open-product">${product(k)}<div><p class="eyebrow">DEBUT EDITION 26/27</p><h3>${PRODUCT[k][0]}</h3><p>${PRODUCT[k][2]}</p></div><footer><b>×${inventory[k]||0}</b>${inventory[k]?`<button class="primary" data-open="${k}">Open 1</button>`:'<span class="muted">None sealed</span>'}</footer></article>`).join('')}</section></section>`;bind();}
function opening(){const o=state.activeOpening;if(!o)return open();const last=o.revealed?.at(-1);root.innerHTML=`<section class="page opening-account"><header class="opening-account-head"><button class="ghost" data-go="open">← Inventory</button><div><p class="eyebrow">SERVER-SEALED OPENING</p><h2>${esc(PRODUCT[o.productKey]?.[0]||'APEX Opening')}</h2><p class="muted">Pack ${Number(o.currentPack)+1} of ${o.packCount} · card ${Number(o.currentReveal)+1} of 3</p></div></header><div class="opening-account-stage">${last?`<div class="revealed-card">${card(last.cardCode)}<p>${esc(cardInfo(last.cardCode).name)} added to your binder.</p></div>`:'<div class="reveal-back"><img src="assets/brand/apex-mark-a-diamond.svg" alt=""><b>APEX</b><small>DEBUT EDITION</small></div>'}</div><footer class="opening-action"><button class="primary" id="reveal">${last?'Reveal next card →':'Tap to reveal →'}</button><p>Unrevealed cards remain private until this button is pressed.</p></footer></section>`;root.querySelector('#reveal').onclick=async e=>{e.currentTarget.disabled=true;e.currentTarget.textContent='Revealing…';try{await gameApi('open.reveal',{openingId:o.id});await refresh();state.activeOpening?opening():recap();}catch(err){e.currentTarget.disabled=false;e.currentTarget.textContent=err.message;}};}
function recap(){root.innerHTML=`<section class="page recap-account"><p class="eyebrow">OPENING COMPLETE</p><h1>Added to your binder.</h1><p class="muted">Your cards, inventory and progression have been saved to your APEX account.</p><button class="primary" data-go="open">Open another →</button></section>`;bind();}
function collection(){root.innerHTML=`<section class="page"><div class="page-title-row"><div><p class="eyebrow">APEX UCL DEBUT EDITION 26/27</p><h1>Your binder</h1></div><span class="collection-count">${state.cards?.length||0}/124 unique</span></div><section class="account-card-grid binder-account">${state.cards?.map(c=>card(c.id,c.quantity)).join('')||'<div class="empty-state">Your binder is waiting for its first pull.</div>'}</section></section>`;}
function store(){root.innerHTML=`<section class="page"><div class="page-title-row"><div><p class="eyebrow">COIN STORE</p><h1>Stock up.</h1></div></div><section class="store-account"><article>${product('normal')}<div><p class="eyebrow">3 CARDS · STANDARD ODDS</p><h2>Normal Pack</h2><p>Build Debut Edition one server-sealed pack at a time.</p><footer><b>200 ◉</b><button class="primary" id="buy">Buy pack</button></footer></div></article></section></section>`;root.querySelector('#buy').onclick=async e=>{e.currentTarget.disabled=true;try{await gameApi('purchase',{productKey:'normal'});await refresh();store();}catch(err){e.currentTarget.disabled=false;e.currentTarget.textContent=err.message;}};}
function profile(){root.innerHTML=`<section class="page profile-account"><p class="eyebrow">APEX ACCOUNT</p><h1>${esc(state.profile?.display_name||'Collector')}</h1><p class="muted">@${esc(state.profile?.username||'apex-collector')}</p><article class="generic-card"><p class="eyebrow">YOUR DATA</p><h3>Secure cloud save</h3><p class="muted">Cards, coins and active openings live on your APEX account—not this device.</p><button class="ghost" id="logout">Sign out</button></article></section>`;root.querySelector('#logout').onclick=async()=>{await signOut();state=null;auth();};}
function soon(name){root.innerHTML=`<section class="page coming-soon"><p class="eyebrow">APEX ONLINE</p><h1>${name}</h1><p class="muted">This mode is next in the secure online migration. Your account and binder are ready for it.</p><button class="primary" data-go="home">Back home</button></section>`;bind();}
function bind(){root.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>route(b.dataset.go));root.querySelectorAll('[data-open]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await gameApi('open.start',{productKey:b.dataset.open,quantity:1});await refresh();opening();}catch(err){b.disabled=false;b.textContent=err.message;}});}
function route(name='home'){chrome(true);setChrome();if(state.activeOpening&&name!=='open')return opening();if(name==='home')home();else if(name==='open')state.activeOpening?opening():open();else if(name==='collection')collection();else if(name==='store')store();else if(name==='profile')profile();else soon(name==='objectives'?'Objectives':name==='draft'?'Quick Draft':'Pack Rush');window.scrollTo({top:0,behavior:'smooth'});}
async function boot(){const {data:{session}}=await supabase.auth.getSession();if(!session)return auth();await refresh();if(!state.profile?.onboarding_completed)return onboarding();route('home');}
supabase.auth.onAuthStateChange((_event,session)=>{if(!session){state=null;auth();}});
boot().catch(err=>auth('signin',err.message));
